---
- name: Deploy application to Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Check if kubectl is installed
      command: kubectl version --client
      register: kubectl_check
      ignore_errors: yes

    - name: Install kubectl if not present
      apt:
        name: kubectl
        state: present
      when: kubectl_check.failed

    - name: Check if minikube is installed
      command: minikube version
      register: minikube_check
      ignore_errors: yes

    - name: Install minikube if not present
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: "0755"
      when: minikube_check.failed

    # Other tasks to check and install Node.js, npm, Python, etc.

    - name: Check if Node.js is installed
      command: node --version
      register: node_check
      ignore_errors: yes

    - name: Install Node.js if not present
      apt:
        name: nodejs
        state: present
      when: node_check.failed

    - name: Check if npm is installed
      command: npm --version
      register: npm_check
      ignore_errors: yes

    - name: Install npm if not present
      apt:
        name: npm
        state: present
      when: npm_check.failed

    - name: Check if Python is installed
      command: python3 --version
      register: python_check
      ignore_errors: yes

    - name: Install Python if not present
      apt:
        name: python3
        state: present
      when: python_check.failed

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present
      when: python_check.failed

    - name: Clone the MailService repository
      git:
        repo: https://github.com/deep-bansal/MailService.git
        dest: /home/{{ ansible_user }}/MailService
        version: main # Change branch name if needed

    - name: Apply backend Persistent Volume
      command: kubectl apply -f kubernetes/backend-pv.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    - name: Apply backend Persistent Volume Claim
      command: kubectl apply -f kubernetes/backend-pvc.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    - name: Apply MongoDB environment configuration
      command: kubectl apply -f kubernetes/mongo-env.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    - name: Apply MongoDB deployment
      command: kubectl apply -f kubernetes/mongo-deployment.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    - name: Apply MongoDB service
      command: kubectl apply -f kubernetes/mongo-service.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    - name: Apply backend environment configuration
      command: kubectl apply -f kubernetes/backend-env.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    - name: Apply backend deployment
      command: kubectl apply -f kubernetes/backend-deployment.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    - name: Apply backend service
      command: kubectl apply -f kubernetes/backend-service.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    - name: Apply frontend deployment
      command: kubectl apply -f kubernetes/frontend-deployment.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    - name: Apply frontend service
      command: kubectl apply -f kubernetes/frontend-service.yaml --validate=false
      args:
        chdir: /home/{{ ansible_user }}/MailService
      environment:
        KUBECONFIG: "/home/iiitb/.kube/config"

    # Other tasks to apply Kubernetes configurations for MongoDB, backend, frontend, etc.
