---
- name: Run Docker Compose
  hosts: localhost
  connection: local
  tasks:
  
    - name: Run Docker Compose
      docker_compose:
        project_src: /Users/deepbansal/Desktop/InboxCOM/docker-compose.yaml
        state: present
