---
- name: Run Docker Compose
  hosts: localhost
  connection: local
  tasks:
  
   - name: Run Docker Compose
      command: "/usr/local/bin/docker-compose -f /Users/deepbansal/Desktop/InboxCOM/docker-compose.yaml up -d"
