apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    group: mail
spec:
  selector:
    pod: mail
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
