apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  volumeName: backend-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources: # which resources we wanna claim for this claim
    requests:
      storage: 500Mi
