apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    group: mail
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
